

---

string CONFIG_CYLINDER="cylinder"
string CONFIG_BOX="box"
string CONFIG_SPHERE="sphere"
string CONFIG_ALL="default"

grasping_msgs/Object[] objects           # filled with point cloud segments and support_surface name to use
grasping_msgs/Object[] support_surfaces  # filled with surfaces (like table) using same names as referred to by objects
string[] config_names                   # config for each object to fit, empty means default

